name: 'Npm registry setup'
description: 'Setup private Matterway registry'
inputs:
  token:
    description: registry token
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        npm set @matterway:registry https://registry.matterway.io
        npm config set //registry.matterway.io/:_authToken ${{ inputs.token }}
      shell: bash
